font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# Foreground & Background
foreground            #00f0ff
background            #0a0a0f

# Cursor
cursor                #ff003c
cursor_text_color     #0a0a0f

# Terminal Colors
# Color0: Black / Color8: Bright Black
color0                #0a0a0f
color8                #202030

# Color1: Red / Color9: Bright Red
color1                #ff003c
color9                #ff3366

# Color3: Yellow / Color11: Bright Yellow
color3                #fcee09
color11               #fffa65

# Color6: Cyan / Color14: Bright Cyan
color6                #00f0ff
color14               #66f5ff
